advanced-lore: true


potions:
  Potion of return:
    keys:
    - "this key is here"

    player-commands: 
    - "say hello"
    console-commands: 
    - "say goodbye"
    permission: "activepotions.return"
    color: 0x444aba
    uses: 1
    ingredients:
    # - type: KeyedItem
    #   key: "activepotions:Potion of Return"
    #   amount: 1
    - type: Item
      material: NETHER_WAART
      amount: 2
